name: mobile_number
description: A Flutter plugin for fetching the device's mobile number or list sim cards data
version: 3.0.0
homepage: https://github.com/amorenew/Flutter-Mobile-Number-Plugin

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.amorenew.mobile_number
        pluginClass: MobileNumberPlugin
